obstacle_range: 4.0
raytrace_range: 4.0
footprint: [[0.3, 0.25], [-0.3, 0.25], [-0.3, -0.25], [0.3, -0.25]]
robot_radius: 0.3

resolution: 0.05
transform_tolerance: 0.2

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: sensor_laser_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

plugins:
    - {name: static_map, type: "costmap_2d::StaticLayer"}
    - {name: obstacles, type: "costmap_2d::VoxelLayer"}
    - {name: detected_path_layer, type: "costmap_2d::DetectedPathLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}