global_costmap:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 5.0
    static_map: true
    rolling_window: false
    cost_scaling_factor: 4.0
    inflation_radius: 0.8
    map_type: costmap