local_costmap:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 5.0
    static_map: false
    rolling_window: true
    width: 8.0
    height: 8.0
    cost_scaling_factor: 4.0
    inflation_radius: 0.4
    map_type: costmap