TrajectoryPlannerROS:
    # Robot Configuration Parameters
    acc_lim_x: 2.0
    acc_lim_y: 0.0
    acc_lim_theta: 2.0

    max_vel_x: 1.0
    min_vel_x: 0.1

    max_vel_theta: 3.14
    min_vel_theta: -3.14
    min_in_place_vel_theta: 0.4

    escape_vel: -0.2

    holonomic_robot: false

    # Goal Tolerance Parameters
    yaw_goal_tolerance: 0.05
    xy_goal_tolerance: 0.1
    latch_xy_goal_tolerance: true

    # Forward Simulation Parameters
    sim_time: 1.0
    sim_granularity: 0.025
    angular_sim_granularity: 0.025
    vx_samples: 3
    vth_samples: 20
    controller_frequency: 20.0

    # Trajectory Scoring Parameters
    meter_scoring: true
    pdist_scale: 0.6
    gdist_scale: 0.8
    occdist_scale: 0.01
    heading_lookahead: 0.325
    heading_scoring: true
    heading_scoring_timestep: 0.8
    # dwa: false
    publish_cost_grid_pc: false
    global_frame_id: odom

    # Oscillation Prevention Parameters
    oscillation_reset_dist: 0.05

    # Global Plan Parameters
    prune_plan: true