<?xml version="1.0"?>
<robot name="shoddy" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:macro name="camera_macro" params="name parent">
        <!-- Properties -->
        <!-- Lens -->
        <xacro:property name="lens_radius" value="0.015"/>
        <xacro:property name="lens_length" value="0.04"/>

        <xacro:property name="lens_shift_x" value="${box_size_x/2}"/>
        
        <xacro:property name="lens_material" value="Black"/>

        <!-- Box -->
        <xacro:property name="box_size_x" value="0.07"/>
        <xacro:property name="box_size_y" value="0.05"/>
        <xacro:property name="box_size_z" value="0.05"/>

        <xacro:property name="box_material" value="DarkGrey"/>

        <!-- Base -->
        <xacro:property name="base_radius" value="0.01"/>
        <xacro:property name="base_length" value="0.28"/>

        <xacro:property name="origin_x" value="0.1"/>
        <xacro:property name="origin_y" value="0.0"/>
        <xacro:property name="origin_z" value="${0.084 + base_shift_z}"/>

        <xacro:property name="base_shift_z" value="${base_length/2}"/>

        <xacro:property name="pitch" value="${pi/10}"/>

        <xacro:property name="base_material" value="Grey"/>



        <!-- Links -->
        <!-- Lens -->
        <link name="${name}">    
            <visual>
                <origin xyz="${lens_shift_x} 0 0" rpy="0 ${pi/2} 0"/>
                <geometry>
                    <cylinder radius="${lens_radius}" length="${lens_length}"/>
                </geometry>
                <material name="${lens_material}"/>
            </visual>

            <collision>
                <geometry>
                    <cylinder radius="${lens_radius}" length="${lens_length}"/>
                </geometry>
                <origin xyz="${lens_shift_x} 0 0" rpy="0 ${pi/2} 0"/>
            </collision>

            <inertial>
                <origin xyz="${lens_shift_x} 0 0" rpy="0 ${pi/2} 0"/>
                <mass value="0.0"/>
                <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
            </inertial>
        </link>

        <joint name="camera_lens_joint" type="fixed">
            <origin xyz="${origin_x} ${origin_y} ${origin_z + base_shift_z}" 
                    rpy="0 ${pitch} 0"/>
            <parent link="${parent}"/>
            <child link="${name}"/>
        </joint>

        <gazebo reference="${name}">   
            <material>Gazebo/Black</material>
        </gazebo>

        <!-- Box -->
        <link name="camera_box_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${box_size_x} ${box_size_y} ${box_size_z}"/>
                    <!-- <mesh filename="package://mrvk_description/meshes/camera/model.dae" scale="0.5 0.5 0.5"/> -->
                </geometry>
                <material name="${box_material}"/>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${box_size_x} ${box_size_y} ${box_size_z}"/>
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.0"/>
                <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
            </inertial>
        </link>

        <joint name="camera_box_joint" type="fixed">
            <origin xyz="${origin_x} ${origin_y} ${origin_z + base_shift_z}" 
                    rpy="0.0 ${pitch} 0.0"/>
            <parent link="${parent}"/>
            <child link="camera_box_link"/>
        </joint>

        <gazebo reference="camera_box_link">
            <material>Gazebo/DarkGrey</material>
        </gazebo>

        <!-- Base -->
        <link name="camera_base_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${base_radius}" length="${base_length}"/>
                </geometry>
                <material name="${base_material}"/>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${base_radius}" length="${base_length}"/>
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.0"/>
                <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
            </inertial>
        </link>

        <joint name="camera_base_joint" type="fixed">
            <origin xyz="${origin_x} ${origin_y} ${origin_z}" rpy="0 0 0"/>
            <parent link="${parent}"/>
            <child link="camera_base_link"/>
        </joint>

        <gazebo reference="camera_base_link">
            <material>Gazebo/Grey</material>
        </gazebo>
    </xacro:macro>
</robot>   