<?xml version="1.0"?>
<robot name="shoddy" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:macro name="ultrasonic_sensor_macro" params="name xyz parent">
        <!-- Properties ==================================================== -->
        <!-- Ultrasonic sensor -->
        <xacro:property name="ultrasonic_sensor_radius" value="0.02"/>
        <xacro:property name="ultrasonic_sensor_length" value="0.005"/>

        <xacro:property name="ultrasonic_sensor_left_xyz" value="${base_size_x/2 + ultrasonic_sensor_length/2} ${-base_size_y/2*0.6} 0.05"/>
        <xacro:property name="ultrasonic_sensor_middle_xyz" value="${base_size_x/2 + ultrasonic_sensor_length/2} 0.0 -0.03"/>
        <xacro:property name="ultrasonic_sensor_right_xyz" value="${base_size_x/2 + ultrasonic_sensor_length/2} ${base_size_y/2*0.6} 0.05"/>
        
        <xacro:property name="ultrasonic_sensor_x"/>
        <xacro:property name="ultrasonic_sensor_y"/>
        <xacro:property name="ultrasonic_sensor_z"/>
        
        <xacro:property name="ultrasonic_sensor_material" value="Grey"/>
        <!-- ==================================================== Properties -->



        <!-- Links ========================================================= -->
        <link name="${name}">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 ${pi/2} 0.0"/>
                <geometry>
                    <cylinder radius="${ultrasonic_sensor_radius}" length="${ultrasonic_sensor_length}"/>
                </geometry>
                <material name="${ultrasonic_sensor_material}"/>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 ${pi/2} 0.0"/>
                <geometry>
                    <cylinder radius="${ultrasonic_sensor_radius}" length="${ultrasonic_sensor_length}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 ${pi/2} 0.0"/>
                <mass value="0.0"/>
                <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
            </inertial>
        </link>
        
        <joint name="${name}_joint" type="fixed">
            <origin xyz="${xyz}" rpy="0.0 0.0 0.0"/>
            <parent link="${parent}"/>
            <child link="${name}"/>
        </joint>

        <gazebo reference="${name}">
            <material>Gazebo/Grey</material>
        </gazebo>
        <!-- ========================================================= Links -->
    </xacro:macro>
</robot>