<?xml version="1.0"?>
<robot name="shoddy" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:macro name="wheel_macro" params="side part origin parent">
        <!-- Properties -->
        <xacro:property name="radius" value="0.115"/>
        <xacro:property name="length" value="0.065"/>
        <xacro:property name="mass" value="0.5"/>

        <xacro:property name="Cr" value="${0.001/0.033}"/>
        <xacro:property name="Cl" value="${0.001/0.018}"/>



        <!-- Link -->
        <link name="wheel_${side}_${part}_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <!-- <cylinder radius="${radius}" length="${length}"/> -->
                    <mesh filename="package://mrvk_description/meshes/wheels/${side}_tire.stl"
                          scale="${Cr*radius} ${Cl*length} ${Cr*radius}"/>
                </geometry>
                <material name="Black"/>
            </visual>
            
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
                <mass value="${mass}"/>
                <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
            </inertial>
        </link>

        <joint name="wheel_${side}_${part}_to_base_joint" type="continuous">
            <axis xyz="0 1 0"/>
            <origin xyz="${origin}" rpy="0.0 0.0 0.0"/>
            <parent link="${parent}"/>
            <child link="wheel_${side}_${part}_link"/>
        </joint>

        <transmission name="wheel_${side}_${part}_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="wheel_${side}_${part}_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>

            <joint name="wheel_${side}_${part}_to_base_joint">
                <hardwareInterface>VelocityJointInterface</hardwareInterface>''
            </joint>
        </transmission>

        <!-- <gazebo reference="${side}_${part}_wheel">
            <mu1 value="200.0"/>
            <mu2 value="100.0"/>
            <kp value="100000.0"/>
            <kd value="1.0" />
            <material>Gazebo/FlatBlack</material>
        </gazebo> -->

        <gazebo reference="wheel_${side}_${part}_link">
            <mu1 value="1.0"/>
            <mu2 value="1.0"/>
            <kp value="100000.0"/>
            <kd value="1.0"/>
            <material>Gazebo/FlatBlack</material>
        </gazebo>
    </xacro:macro>
</robot>   