type: "diff_drive_controller/DiffDriveController"
publish_rate: 50

left_wheel: ['wheel_left_front_to_base_joint', 'wheel_left_back_to_base_joint']
right_wheel: ['wheel_right_front_to_base_joint', 'wheel_right_back_to_base_joint']


pose_covariance_diagonal : [0.00001, 0.00001, 0.00001, 0.00001, 0.00001, 0.00001]
twist_covariance_diagonal: [0.00001, 0.00001, 0.00001, 0.00001, 0.00001, 0.00001]

base_frame_id: base_link

wheel_separation_multiplier: 1.25 # husky 1.875 - Will need to adjust based on odom readings
wheel_radius_multiplier    : 1

enable_odom_tf: false
estimate_velocity_from_position: false

linear:
  x:
    has_velocity_limits    : true
    max_velocity           : 0.2   # m/s
    has_acceleration_limits: true
    max_acceleration       : 0.6   # m/s^2
angular:
  z:
    has_velocity_limits    : true
    max_velocity           : 2.0   # rad/s
    has_acceleration_limits: true
    max_acceleration       : 6.0   # rad/s^2